# SITE CONFIGURATION
baseurl: ""
url: "http://rubynostrilhos.com.br/"

theme_settings:
  # Meta
  title: Ruby nos trilhos
  avatar: assets/img/ruby-nos-trilhos-logo.jpg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Ruby on Rails e muito mais em pt-br."

  # Header and footer text
  header_text: >
     <p>Ruby on Rails<br><small>e muito mais em pt-br.</small></p>
  header_text_feature_image: assets/img/ruby-on-rails.png
  footer_text: >
    "O futuro do Ruby é brilhante, mas depende de nós." <a href="https://twitter.com/rafaelfranca">Rafael Fraça</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "rubynostrilhos"
  flickr:
  gitlab:
  github: "rubynostrilhos"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "rubynostrilhos"
  wordpress:
  youtube:

  # Scripts / Features
  google_analytics: "UA-110013614-1"
  disqus_shortname: ruby-nos-trilhos
  katex: true # Enable if using math markup
  search: true
  tags: false

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
