baseurl: ""
url: "https://rubynostrilhos.com.br"
title: "Ruby nos trilhos"
author: "Lucas Oliveira"
description: "Ruby on Rails e muito mais em pt-br."

toggles:
  thumbnails: false

theme_settings:
  avatar: "assets/img/rubynostrilhos.jpg"
  favicon: "assets/favicon.ico"
  description: "Blog sobre Ruby on Rails, carreira, devops e muito mais em pt-br."

  # Icons
  rss: true
  facebook: "rubynostrilhos"
  github: "rubynostrilhos"
  twitter: "rubynostrilhos"

  google_analytics: "UA-110013614-1"
  disqus_shortname: ruby-nos-trilhos

  katex: false # Enable if using math markup
  search: false
  tags: true

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Próximo"
  str_previous_post: "Anterior"
  str_next_page: "Próximo"
  str_previous_page: "Anterior"
  str_continue_reading: "continue lendo"
  str_javascript_required_disqus: "Por favor habilite o JavaScript para ver os comentários."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
